services:
  blog-public-client:
    build: .
    container_name: blog-public-client
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - blog-realm-network

networks:
  blog-realm-network:
    external: true
